Add locking functionality for model training
greenFantasy/cs197-final-project pull request #9
Opened 2022-11-21 23:42 UTC by ktingos

2022-11-21 23:43 UTC, ktingos commented
All these commits were created be me but the instance had been logged in for github under Aakash so it looks like he made them.

2022-11-24 03:57 UTC, christyjestin requested changes
See comments; looks good otherwise

2022-11-24 03:57 UTC, christyjestin commented on run_train.py
> +        params_list.append({params_key: model.text_projection})
We should be training the projection head no matter what right? Otherwise it's just being projected to some random space and making the task potentially harder?

2022-11-24 03:57 UTC, christyjestin commented on run_train.py
> +            params_list.append({params_key: model.token_embedding.parameters()})
just to confirm, the tokenizer and positional embedding attributes are only part of the CheXzero text transformer, but the model object could be either CheXzero or CXR Bert?

2022-11-24 03:57 UTC, christyjestin commented on run_train.py
> +    params_key = 'params'
it's probably better practice to append just the parameters into the list, and then afterwards do a list comprehension like [{'params': param} for param in params_list] before passing into the optimizer (so that you're not repeating the same code) but not a real issue

The bigger thing is that it looks like you only use this dictionary syntax when you do parameter groups and set separate learning rates per group; it doesn't look like we're doing that, so it should be enough to just pass in a list of parameters without the dictionary syntax

2022-11-24 03:58 UTC, christyjestin commented on run_train.py
> +            params_list.append({params_key: model.token_embedding.parameters()})
either of those two plus a vision tower?

2022-11-24 04:01 UTC, ktingos commented on run_train.py
> +    params_key = 'params'
Will make that first adjustment.

In terms of your second comment, Aakash was the one who had set up the dictionary syntax. I had played with it quickly to see if It could just be a list but I remember getting an error so I went back to using the dictionary style.

2022-11-24 04:03 UTC, ktingos commented on run_train.py
> +        params_list.append({params_key: model.text_projection})
Yes. After our discussion from today I realize that is what Aakash had done so I will change the code so the text projection is always part of the parameters list.

2022-11-24 04:07 UTC, ktingos commented on run_train.py
> +            params_list.append({params_key: model.token_embedding.parameters()})
Yes that is correct. See the below screenshot for the forward pass of the text stack. The first condition is for chexzero (and it's the original code that we haven't edited) and the second condition is for cxrbert. 
<img width="819" alt="image" src="https://user-images.githubusercontent.com/43186135/203691786-6c213c7e-b171-4c71-a539-69a3de969ac5.png">

2022-11-24 18:29 UTC, merged